In [4]:
#importing libraries
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
import pickle

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
#loading the data
kidney_data = pd.read_csv("/content/drive/MyDrive/Multiple diseases prediction system /kidney.csv")
#printing first 5 rows
kidney_data.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [7]:
#shape of the data(rows and columns)
kidney_data.shape

(400, 26)

In [8]:
#list of columns to retain
column_to_retain = ['sg', 'al', 'sc', 'hemo', 'pcv', 'wbcc', 'rbcc', 'htn', 'classification']

#droping the rest columns
kidney_data = kidney_data.drop([col for col in kidney_data.columns if not col in column_to_retain] , axis=1)

#drop the rows with na or missing values
kidney_data = kidney_data.dropna(axis=0)

In [9]:
kidney_data.head()

      sg   al   sc  hemo pcv  htn classification
0  1.020  1.0  1.2  15.4  44  yes            ckd
1  1.020  4.0  0.8  11.3  38   no            ckd
2  1.010  2.0  1.8   9.6  31   no            ckd
3  1.005  4.0  3.8  11.2  32  yes            ckd
4  1.010  2.0  1.4  11.6  35   no            ckd

In [12]:
import pandas.api.types as ptypes

#transform the non-numeric data in the columns
for column in kidney_data.columns:
    if ptypes.is_numeric_dtype(kidney_data[column]):
        continue
    kidney_data[column] = LabelEncoder().fit_transform(kidney_data[column])

In [13]:
#printing the first 5 rows of the cleaned data
kidney_data.head(20)

       sg   al    sc  hemo  pcv  htn  classification
0   1.020  1.0   1.2  15.4   28    1               0
1   1.020  4.0   0.8  11.3   22    0               0
2   1.010  2.0   1.8   9.6   15    0               0
3   1.005  4.0   3.8  11.2   16    1               0
4   1.010  2.0   1.4  11.6   19    0               0
5   1.015  3.0   1.1  12.2   23    1               0
6   1.010  0.0  24.0  12.4   20    0               0
7   1.015  2.0   1.1  12.4   28    0               0
8   1.015  3.0   1.9  10.8   17    1               0
9   1.020  2.0   7.2   9.5   13    1               0
10  1.010  2.0   4.0   9.4   12    1               0
11  1.010  3.0   2.7  10.8   16    1               0
12  1.015  3.0   2.1   9.7   12    1               0
14  1.010  3.0   4.1   5.6    3    1               0
15  1.015  3.0   9.6   7.6    8    1               0
18  1.025  0.0   1.3  12.7   21    1               0
19  1.015  1.0   1.6  10.3   14    1               0
20  1.015  2.0   3.9   7.7    8    1               0
22  1.025  4.0   7.7   9.8   16    1               0
24  1.015  4.0   1.4  11.1   23    1               0

In [14]:
kidney_data.tail(20)

        sg   al   sc  hemo  pcv  htn  classification
380  1.020  0.0  1.1  15.3   38    0               1
381  1.025  0.0  0.5  16.6   24    0               1
382  1.025  0.0  0.8  16.8   35    0               1
383  1.025  0.0  0.7  13.9   33    0               1
384  1.020  0.0  1.1  15.4   26    0               1
385  1.020  0.0  0.6  16.5   36    0               1
386  1.025  0.0  0.5  16.4   27    0               1
387  1.025  0.0  0.9  16.7   34    0               1
388  1.020  0.0  1.2  15.5   30    0               1
389  1.025  0.0  0.7  17.0   36    0               1
390  1.025  0.0  0.8  15.0   36    0               1
391  1.025  0.0  1.1  15.6   28    0               1
392  1.020  0.0  1.2  14.8   30    0               1
393  1.025  0.0  0.7  13.0   38    0               1
394  1.020  0.0  0.8  14.1   29    0               1
395  1.020  0.0  0.5  15.7   31    0               1
396  1.025  0.0  1.2  16.5   38    0               1
397  1.020  0.0  0.6  15.8   33    0               1
398  1.025  0.0  1.0  14.2   35    0               1
399  1.025  0.0  1.1  15.8   37    0               1

In [16]:
kidney_data.shape

(287, 7)

In [17]:
#split the data into independent (X) data set (the features) and dependent (Y) data set (the target)
X = kidney_data.drop(['classification'], axis=1)
Y = kidney_data['classification']

In [18]:
#feature scaling
x_scaler = MinMaxScaler()
X_scaled = x_scaler.fit_transform(X)

In [19]:
#splitting the dataset into 80% training and 20% testing and shuffle
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42 ,shuffle=True)

In [20]:
# Initialize SVM classifier
model = SVC(kernel='linear', random_state=42)

In [21]:
# Train the SVM classifier
model.fit(X_train, Y_train)

SVC(kernel='linear', random_state=42)

In [22]:
# Predict labels for training and testing sets
train_predictions = model.predict(X_train)
test_predictions = model.predict(X_test)

# Compute training and testing accuracy
train_accuracy = accuracy_score(Y_train, train_predictions)
test_accuracy = accuracy_score(Y_test, test_predictions)

print("Training Accuracy:", train_accuracy)
print("Testing Accuracy:", test_accuracy)

Training Accuracy: 0.9781659388646288
Testing Accuracy: 0.9655172413793104

In [23]:
import pickle

In [24]:
#saving the model
filename = 'kidney_prediction_model.sav'
pickle.dump(model, open(filename, 'wb'))

In [25]:
#shape of the training and testing data
print("Shape of the training data:", X_train.shape)
print("Shape of the testing data:", X_test.shape)

Shape of the training data: (229, 6)
Shape of the testing data: (58, 6)

In [26]:
#show the actual and predicted values
predict = model.predict(X_test)
predict = [1 if y>=0.5 else 0 for y in predict]

print('Original : {0}'.format(",".join(str(x) for x in Y_test)))
print('Predicted : {0}'.format(",".join(str(x) for x in predict)))

Original : 0,1,0,1,1,1,0,0,0,0,0,1,0,1,0,1,1,1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,1,1,0,1,1,0,1,1,1,1,0,0,1,0
Predicted : 0,1,0,1,1,1,0,0,0,0,0,1,0,1,0,1,1,1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0,1,1,0,0,0,0,1,1,0,1,1,0,1,1,1,1,0,0,1,0

In [27]:
Y_test

9      0
368    1
235    0
318    1
341    1
300    1
155    0
111    0
173    0
44     0
225    0
311    1
234    0
379    1
5      0
333    1
348    1
367    1
63     0
382    1
349    1
80     0
249    0
250    1
179    0
172    0
246    0
239    0
177    0
56     0
178    0
240    0
269    1
317    1
65     0
130    0
94     0
185    0
115    0
260    1
241    0
40     0
27     0
31     0
284    1
366    1
133    0
272    1
381    1
150    0
309    1
267    1
275    1
259    1
6      0
123    0
296    1
91     0
Name: classification, dtype: int64

In [31]:
input_data = [[1.02,0,0.7,13.2,28,0]]

# Get feature names from the original training data X
feature_names = X.columns

# Create a DataFrame from input_data with the correct feature names
input_df = pd.DataFrame(input_data, columns=feature_names)

# Scale the input data using the fitted scaler
input_data_scaled = x_scaler.transform(input_df)

# Convert the scaled data back to a DataFrame with feature names
input_data_scaled_df = pd.DataFrame(input_data_scaled, columns=feature_names)

# Make prediction using the trained model
prediction = model.predict(input_data_scaled_df)
print(prediction)

if (prediction[0]== 0):
  print('The Person does not have a Kidney Disease')
else:
  print('The Person has Kidney Disease')

[0]
The Person does not have a Kidney Disease

In [32]:
# loading the saved model
loaded_model = pickle.load(open('kidney_prediction_model.sav', 'rb'))

In [33]:
for column in X.columns:
  print(column)

sg
al
sc
hemo
pcv
htn